apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "balloon.fullname" . }}
  labels:
    {{- include "balloon.labels" . | nindent 4 }}
spec:
  # replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "balloon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        fireflies.ai/app: {{ include "balloon.fullname" . }}
        {{- include "balloon.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: {{ include "balloon.fullname" . }}
      terminationGracePeriodSeconds: 0
