apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "balloon.fullname" . }}
value: {{ .Values.priority }}
preemptionPolicy: Never
globalDefault: false
description: "Balloon pod priority"