{{- if .Values.backendConfig.enabled }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  annotations:
    {{- include "app.annotations" . | nindent 4 }}
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  timeoutSec: 1800
{{- end }}
