{{- with .Values.secrets -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  annotations:
    {{- include "app.annotations" $ | nindent 4 }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  name: {{ .name }}
spec:
  backendType: {{ .backend }}
  projectId: {{ .projectId }}
  data:
    {{- range .data }}
    - key: {{ .key }}
      name: {{ .name }}
    {{- end }}
  template:
    metadata:
      annotations:
        {{- include "app.annotations" $ | nindent 8 }}
      labels:
        {{- include "app.labels" $ | nindent 8 }}
{{- end }}