kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fireflies
subjects:
- kind: ServiceAccount
  name: {{ include "fireflies.serviceAccountName" . }}
roleRef:
  kind: Role
  name: fireflies
  apiGroup: rbac.authorization.k8s.io