kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fireflies
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
    verbs:
      - get
      - create
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get